# Generated by Django 5.1.4 on 2025-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_orderitem_product_price_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("heavy", "Heavy"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                blank=True,
                choices=[("fair", "Fair"), ("medium", "Medium"), ("dark", "Dark")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
