# Generated by Django 5.1.4 on 2025-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0016_profile_body_type_profile_height_profile_skin_tone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="physical_attributes_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ectomorph", "Ectomorph"),
                    ("mesomorph", "Mesomorph"),
                    ("endomorph", "Endomorph"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_fair", "Very Fair"),
                    ("fair", "Fair"),
                    ("medium", "Medium"),
                    ("olive", "Olive"),
                    ("brown", "Brown"),
                    ("dark", "Dark"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
    ]
