# Generated by Django 5.1.4 on 2025-03-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_profile_physical_attributes_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="body_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="physical_attributes_completed",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skin_tone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="weight",
        ),
    ]
