# Generated by Django 5.1.4 on 2025-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_userstylepreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="body_shape",
            field=models.CharField(
                default="Rectangle – Hips, shoulders, and waist are the same proportion",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="budget_range",
            field=models.CharField(
                default="Mid-range (High-street brands like Sapphire, Khaadi)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="clothing_size",
            field=models.CharField(default="M", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="clothing_types",
            field=models.CharField(default="Casual", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="favorite_brands",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="hair_color",
            field=models.CharField(default="Black", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="height",
            field=models.CharField(default="5'3\" - 5'6\" (Average)", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                default="Medium Tan (Moderate brown with neutral undertones)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="style_quiz_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="UserStylePreference",
        ),
    ]
