# Generated by Django 5.1.4 on 2025-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_profile_body_shape_profile_budget_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="razorpay_payment_signature",
        ),
        migrations.AlterField(
            model_name="profile",
            name="body_shape",
            field=models.CharField(
                choices=[
                    (
                        "Hourglass",
                        "Hourglass – Waist is the narrowest part of the frame",
                    ),
                    ("Triangle", "Triangle – Hips are broader than shoulders"),
                    (
                        "Rectangle",
                        "Rectangle – Hips, shoulders, and waist are the same proportion",
                    ),
                    ("Oval", "Oval – Hips and shoulders are narrower than waist"),
                ],
                default="Rectangle",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("Budget", "Budget – Affordable brands, local markets"),
                    (
                        "Mid-range",
                        "Mid-range – High-street brands like Sapphire, Khaadi",
                    ),
                    ("Premium", "Premium – Luxury brands like Élan, Sania Maskatiya"),
                    ("It Varies", "It Varies"),
                ],
                default="Mid-range",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="clothing_size",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="M",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="clothing_types",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Workwear", "Workwear"),
                    ("Social occasions", "Social occasions"),
                    ("Maternity", "Maternity"),
                ],
                default="Casual",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_brands",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Khaadi", "Khaadi"),
                    ("Gul Ahmed", "Gul Ahmed"),
                    ("Sapphire", "Sapphire"),
                    ("Bonanza Satrangi", "Bonanza Satrangi"),
                ],
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("Brown", "Brown"),
                    ("Dyed", "Dyed (Blonde, Red, Balayage, etc.)"),
                    ("Other", "Other"),
                ],
                default="Black",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.CharField(
                choices=[
                    ("Under 5'2\"", "Under 5'2\" (Petite)"),
                    ("5'3\" - 5'6\"", "5'3\" - 5'6\" (Average)"),
                    ("5'7\" - 5'10\"", "5'7\" - 5'10\" (Tall)"),
                    ("Above 5'10\"", "Above 5'10\""),
                ],
                default="5'3\" - 5'6\" (Average)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                choices=[
                    ("Light", "Light – Very fair or pale"),
                    ("Wheatish", "Wheatish – Fair with warm undertones"),
                    (
                        "Medium Tan",
                        "Medium Tan – Moderate brown with neutral undertones",
                    ),
                    ("Deep Brown", "Deep Brown – Dark complexion"),
                ],
                default="Medium Tan",
                max_length=100,
            ),
        ),
    ]
