# Generated by Django 5.1.4 on 2025-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_cart_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("Budget", "Budget – Affordable brands, local markets"),
                    (
                        "Mid-range",
                        "Mid-range – High-street brands like Sapphire, Khaadi",
                    ),
                    ("Premium", "Premium – Luxury brands like Élan, Sania Maskatiya"),
                    ("Varies", "It Varies"),
                ],
                default="Mid-range",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="clothing_types",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Workwear", "Workwear"),
                    ("Social", "Social occasions"),
                    ("Maternity", "Maternity"),
                ],
                default="Casual",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.CharField(
                choices=[
                    ("Short", "Under 5'2\" (Petite)"),
                    ("Average", "5'3\" - 5'6\" (Average)"),
                    ("Above_average", "5'7\" - 5'10\" (Above Average)"),
                    ("Tall", "Above 5'10\""),
                ],
                default="Average",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                choices=[
                    ("Light", "Light – Very fair or pale"),
                    ("Wheatish", "Wheatish – Fair with warm undertones"),
                    ("Tan", "Medium Tan – Moderate brown with neutral undertones"),
                    ("Brown", "Deep Brown – Dark complexion"),
                ],
                default="Tan",
                max_length=100,
            ),
        ),
    ]
