# Generated by Django 5.1.4 on 2025-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_profile_hair_color_remove_profile_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="body_shape",
            field=models.CharField(
                choices=[
                    ("Hourglass", "Hourglass"),
                    ("Triangle", "Triangle"),
                    ("Rectangle", "Rectangle"),
                    ("Oval", "Oval"),
                ],
                default="Rectangle",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("Budget", "Budget"),
                    ("Mid-range", "Mid-range"),
                    ("Premium", "Premium"),
                    ("Varies", "Varies"),
                ],
                default="Mid-range",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                choices=[
                    ("Light", "Light"),
                    ("Wheatish", "Wheatish"),
                    ("Tan", "Tan"),
                    ("Brown", "Brown"),
                ],
                default="Tan",
                max_length=100,
            ),
        ),
    ]
