# Generated by Django 5.1.4 on 2025-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0025_alter_profile_body_shape_alter_profile_budget_range_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("Budget", "Budget"),
                    ("Midrange", "Midrange"),
                    ("Premium", "Premium"),
                    ("Varies", "Varies"),
                ],
                default="Mid-range",
                max_length=100,
            ),
        ),
    ]
