# Generated by Django 5.1.4 on 2025-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_productreview_dislikes_productreview_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="body_shape",
            field=models.CharField(default="Rectangle", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="clothing_type",
            field=models.CharField(default="Casual", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="hair_color",
            field=models.CharField(default="Black", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_tone",
            field=models.CharField(default="Medium Tan", max_length=100),
        ),
    ]
