# Generated by Django 5.1.4 on 2025-04-03 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_product_location_tags_product_occasion_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_desription",
            new_name="product_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="body_shape",
        ),
        migrations.RemoveField(
            model_name="product",
            name="clothing_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="hair_color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="skin_tone",
        ),
        migrations.AddField(
            model_name="product",
            name="body_shapes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Hourglass",
                            "Hourglass – Waist is the narrowest part of the frame",
                        ),
                        ("Triangle", "Triangle – Hips are broader than shoulders"),
                        (
                            "Rectangle",
                            "Rectangle – Hips, shoulders, and waist are the same proportion",
                        ),
                        ("Oval", "Oval – Hips and shoulders are narrower than waist"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="clothing_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Casual", "Casual"),
                        ("Workwear", "Workwear"),
                        ("Social", "Social occasions"),
                        ("Maternity", "Maternity"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_tones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Light", "Light – Very fair or pale"),
                        ("Wheatish", "Wheatish – Fair with warm undertones"),
                        ("Tan", "Medium Tan – Moderate brown with neutral undertones"),
                        ("Brown", "Deep Brown – Dark complexion"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Khaadi", "Khaadi"),
                    ("Gul Ahmed", "Gul Ahmed"),
                    ("Sapphire", "Sapphire"),
                    ("Bonanza Satrangi", "Bonanza Satrangi"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="location_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="occasion_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seasonal_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
