# Generated by Django 5.1.4 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0018_rename_product_desription_product_product_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="body_shapes",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Hourglass",
                        "Hourglass – Waist is the narrowest part of the frame",
                    ),
                    ("Triangle", "Triangle – Hips are broader than shoulders"),
                    (
                        "Rectangle",
                        "Rectangle – Hips, shoulders, and waist are the same proportion",
                    ),
                    ("Oval", "Oval – Hips and shoulders are narrower than waist"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="clothing_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Casual", "Casual"),
                    ("Workwear", "Workwear"),
                    ("Social", "Social occasions"),
                    ("Maternity", "Maternity"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="skin_tones",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Light", "Light – Very fair or pale"),
                    ("Wheatish", "Wheatish – Fair with warm undertones"),
                    ("Tan", "Medium Tan – Moderate brown with neutral undertones"),
                    ("Brown", "Deep Brown – Dark complexion"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
